name: country
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.5
  http:
  provider: ^5.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  flutter_calendar_carousel: ^2.0.1
  photo_view: ^0.11.1
  firebase_messaging: ^10.0.0
  firebase_core: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/miniatura.png"
  adaptive_icon_background: "assets/icons/miniatura.png"

flutter:


  uses-material-design: true


  assets:
    - assets/backgrounds/
    - assets/icons/
    - assets/images/

